import { Model, model, ObjectId, Schema } from "mongoose";


interface AutoPlaylistDocument{
    title : string;
    items : ObjectId[],
}

const AutoGeneratedPlaylistSchema = new Schema<AutoPlaylistDocument>({
    title : {
        type: String,
        required :true
    },
    items :[{
        type : Schema.Types.ObjectId,
        require: true,
        ref : ("Audio")
    }],
},{
    timestamps: true
});

export default model("AutoGeneratedPlaylist",  AutoGeneratedPlaylistSchema) as Model<AutoPlaylistDocument>