import { getAutoGeneratedPlaylist, getFollowersProfile, getFollowersProfilePublic, getFollowingsProfile, getIsFollowing, getPlaylistAudios, getPrivatePlaylistAudios, getPublicPlaylist, getPublicProfile, getPublicUploads, getRecommendedByProfile, getUploads, updateFollower } from '#/controllers/profile'
import { isAuth, mustAuth } from '#/middleware/auth'
import Router from 'express'

const router = Router()

//update follower 
router.post('/update-follower/:profileId', mustAuth, updateFollower);

// get uploads by user
router.get('/uploads', mustAuth, getUploads);

// get uploads from public 
router.get('/uploads/:profileId', getPublicUploads);

// get info of a public profie
router.get('/info/:publicId', getPublicProfile);

// get profie playlist
router.get('/playlist/:profileId', getPublicPlaylist);

//get recommended playlist 
router.get("/recommended", isAuth, getRecommendedByProfile)

//get recommended playlist 
router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlaylist)

//get follower for this authenticated user
router.get("/followers", mustAuth, getFollowersProfile)

//get following for this authenticated user
router.get("/followings", mustAuth, getFollowingsProfile)

//get followers profile public for an authenticated user
router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic)

//get audios from a playlist
router.get("/playlist-audios/:playlistId", getPlaylistAudios)

//get audios from a playlist
router.get("/private-playlist-audios/:playlistId", mustAuth,getPrivatePlaylistAudios)  

//get audios from a playlist
router.get("/is-following/:profileId", mustAuth,getIsFollowing)  

export default router