import cron from 'node-cron'
import Audio from '#/models/audio'
import autoGeneratedPlaylist from '#/models/autoGeneratedPlaylist';

// cron.schedule("*/2 * * * * *", ()=>{
//     console.log("Cron is running!")
// })


const generatedPlaylist = async () =>{
    const result = await Audio.aggregate([
        { $sort: { likes: -1 } },
        {
            $sample: {size:20}
        },
        {
          $group: {
            _id: "$category",
            audios: { $push: "$$ROOT._id" },
          },
        },
        
      ]);
    
      result.map(async (item)=>{
        await autoGeneratedPlaylist.updateOne(
            {title: item._id},
            {$set: {items: item.audios}},
            {upsert: true}
        )
      });
};

cron.schedule("0 0 * * *", async ()=>{
   //This will run evey 24 hours
   await generatedPlaylist()
})